name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go 1.18
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
        id: go
      - name: Build Docker image
        run: docker build -f docker/dev/Dockerfile -t go-app .
      - name: Test
        run: docker run go-app sh -c "cd /go/src/app && go build . && make migrate-up && make test"
