name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  MYSQL_USER: root
  MYSQL_PASSWORD: pass
  MYSQL_DATABASE: go_development
  MYSQL_TEST_DATABASE: go_test

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://docker.io/library/golang:1.18
      env:
        MYSQL_USER: root
        MYSQL_PASSWORD: pass
        MYSQL_DATABASE: go_development
        MYSQL_TEST_DATABASE: go_test
        MYSQL_HOST: db
        MYSQL_PORT: 3306
    services:
      db:
        image: mysql:8.0.28
        env:
          MYSQL_ROOT_PASSWORD: pass
          MYSQL_DATABASE: go_development
          MYSQL_ROOT_HOST: '%'
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
          --name db
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: go build -v .
      - name: Test
        run: |
          go test ./... -v
