name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  db:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: pass
          MYSQL_DATABASE: go_development
          MYSQL_TEST_DATABASE: go_test
        ports:
          - 3306:3306
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go 1.18
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
        id: go
      - name: Build Docker image
      - run: docker build -t go-app .
        env:
          MYSQL_USER: root
          MYSQL_PASSWORD: pass
          MYSQL_DATABASE: go_development
          MYSQL_TEST_DATABASE: go_test
          MYSQL_HOST: mysql
          MYSQL_PORT: 3306
      - name: Test
      - run: docker run go-app sh -c "make migrate-up && make test"
        env:
          MYSQL_USER: root
          MYSQL_PASSWORD: pass
          MYSQL_DATABASE: go_development
          MYSQL_TEST_DATABASE: go_test
          MYSQL_HOST: mysql
          MYSQL_PORT: 3306
