name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  MYSQL_USER: root
  MYSQL_PASSWORD: pass
  MYSQL_DATABASE: go_development
  MYSQL_TEST_DATABASE: go_test

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8.0.28
        env:
          MYSQL_ROOT_PASSWORD: pass
          MYSQL_DATABASE: go_development
          MYSQL_ROOT_HOST: '%'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go 1.18
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Build Docker image
        run: docker build  -e "MYSQL_USER=root" -e "MYSQL_PASSWORD=pass" -e "MYSQL_DATABASE=go_development" -e "MYSQL_TEST_DATABASE=go_test" -e "MYSQL_HOST=$db" -e "MYSQL_PORT=3306" -t go-app .
        env:
          MYSQL_HOST: db
      - name: Test
        run: docker run -e "MYSQL_USER=root" -e "MYSQL_PASSWORD=pass" -e "MYSQL_DATABASE=go_development" -e "MYSQL_TEST_DATABASE=go_test" -e "MYSQL_HOST=$db" -e "MYSQL_PORT=3306" go-app sh -c "make migrate-up && make test"
        env:
          MYSQL_HOST: db
